import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { DynamicDialogConfig, DynamicDialogRef } from 'primeng/dynamicdialog';
import { NavigationService } from '../../../services/navigation.service';
import { NavigationItem } from '../../../models/navigation-item.model';

@Component({
  selector: 'app-navigation-form',
  templateUrl: './navigation-form.component.html',
  // styleUrls: ['./navigation-form.component.scss']
})
export class NavigationFormComponent implements OnInit {
  navigationForm: FormGroup;
  isEdit: boolean = false;
  item: NavigationItem | null = null;
  allNavigationItems: NavigationItem[] = [];

  constructor(
    private fb: FormBuilder,
    private navigationService: NavigationService,
    public ref: DynamicDialogRef,
    public config: DynamicDialogConfig
  ) {
    this.navigationForm = this.fb.group({
      name: ['', Validators.required],
      icon: [''],
      route: ['', Validators.required],
      parentId: [''],
      order: [0, Validators.required],
      isVisible: [true]
    });
  }

  ngOnInit(): void {
    // this.loadAllNavigationItems();

    if (this.config.data && this.config.data.item) {
      this.isEdit = true;
      this.item = this.config.data.item;
      this.navigationForm.patchValue({
        name: this.item?.name,
        icon: this.item?.icon || '',
        route: this.item?.route,
        parentId: this.item?.parentId || '',
        order: this.item?.order,
        isVisible: this.item?.isVisible
      });
    }
    this.allNavigationItems = this.config.data.allNavigationItem;
  }

  loadAllNavigationItems(): void {
    this.navigationService.getAllNavigation().subscribe({
      next: (items) => {
        // Only show items that can be parent (not the current item being edited)
        this.allNavigationItems = items;
      },
      error: (error) => {
        console.error('Error loading navigation items for parent selection:', error);
      }
    });
  }

  onSubmit(): void {
    if (this.navigationForm.invalid) {
      return;
    }

    const formValue = this.navigationForm.value;

    // Prepare the navigation item with proper GUID handling
    const parentId = formValue.parentId ? (formValue.parentId === '' ? null : formValue.parentId) : null;

    let navigationItem: NavigationItem = {
      id: this.isEdit ? this.item!.id : '', // For creation, id will be generated by backend
      name: formValue.name,
      icon: formValue.icon || null,
      route: formValue.route,
      parentId: parentId,
      order: formValue.order,
      isVisible: formValue.isVisible
    };

    if (this.isEdit && this.item) {
      // For update, use the existing ID
      this.navigationService.updateNavigationItem(this.item.id, navigationItem).subscribe({
        next: (updatedItem) => {
          this.ref.close(updatedItem);
        },
        error: (error) => {
          console.error('Error updating navigation item:', error);
        }
      });
    } else {
      // For create, remove the empty id field so backend can generate it
      delete (navigationItem as any).id;
      this.navigationService.createNavigationItem(navigationItem).subscribe({
        next: (createdItem) => {
          this.ref.close(createdItem);
        },
        error: (error) => {
          console.error('Error creating navigation item:', error);
        }
      });
    }
  }

  onCancel(): void {
    this.ref.close();
  }
}
